const EXPRESS_REGISTRATION = "EXPRESS_REGISTRATION";
const ADHOC_PAYMENT = "ADHOC_PAYMENT";
const EXCEEDED_LIMIT = "EXCEEDED_LIMIT";

export default ({
    EXPRESS_REGISTRATION,
    ADHOC_PAYMENT,
    EXCEEDED_LIMIT
});


